# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_number',
        ),
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
